[project]
name = "gal-parseupddescription"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "keyboard>=0.13.5",
    "pyinstaller>=6.16.0",
    "python-redmine>=2.5.0",
    "pytz>=2025.2",
]
